[ 2025-07-24 13:09:26,652 ] 59 networksecurity.logging - INFO - Starting data extraction and MongoDB insertion process
[ 2025-07-24 13:09:26,653 ] 64 networksecurity.logging - INFO - File path: Network_Data\phisingData.csv
[ 2025-07-24 13:09:26,653 ] 65 networksecurity.logging - INFO - Database: NetworkSecurity
[ 2025-07-24 13:09:26,653 ] 66 networksecurity.logging - INFO - Collection: NetworkData
[ 2025-07-24 13:09:26,653 ] 29 networksecurity.logging - INFO - Attempting to read CSV file: Network_Data\phisingData.csv
[ 2025-07-24 13:09:26,886 ] 33 networksecurity.logging - INFO - Successfully converted CSV to JSON. Number of records: 11055
[ 2025-07-24 13:09:28,743 ] 41 networksecurity.logging - INFO - Attempting to insert 11055 records into MongoDB database: NetworkSecurity, collection: NetworkData
[ 2025-07-24 13:09:59,186 ] 54 networksecurity.logging - ERROR - Error in insert_data_mongodb: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6881e3308221ca83b0d1624f, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[ 2025-07-24 13:09:59,186 ] 75 networksecurity.logging - ERROR - Error in main execution: Error occured in python script name [E:\Git Repo\network_security_ml\networksecurity\push_data.py] line number [50] error message [localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6881e3308221ca83b0d1624f, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>]
